name: CI/CD Pipeline for FastAPI App

on:
  push:
    branches:
      - main   # You can change this to the branch you want to deploy from (e.g., "master")
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # GitHub secret for Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # GitHub secret for Docker Hub password

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ github.sha }} .

      # Push the Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ github.sha }}

      # Deploy the Docker image (custom step, depending on where you want to deploy)
      - name: Deploy to Server (Optional)
        run: |
          ssh user@your-server-ip "docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ github.sha }} && docker run -d -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ github.sha }}"

